{% set name = "pet-mad" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pet_mad-{{ version }}.tar.gz
  sha256: 84d5d0b09ebb9c4c382e61b70617db1bc863b00cb8864d50db347817265bd08c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=68
    - setuptools-scm >=8
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - metatrain==2025.6
    - huggingface_hub
    - platformdirs

test:
  imports:
    - pet_mad
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/lab-cosmo/pet-mad
  summary: PET-MAD, a Universal Interatomic Potential for Advanced Materials Modeling
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://github.com/lab-cosmo/pet-mad

extra:
  recipe-maintainers:
    - abmazitov
    - Luthaf
