github:
  user_or_org: abmazitov

github_actions:
  timeout_minutes: 1080
  triggers:
  - push
  - pull_request
provider:
  linux_64: github_actions
  osx_64: github_actions
  osx_arm64: github_actions
